name: Build and Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'sample/**'
      - '.github/dita-ot/**'
      - '.github/workflows/docs-gh-pages.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy-docs:
    name: Build & Deploy DITA Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Build DITA AST Documentation
        uses: dita-ot/dita-ot-action@master
        with:
          install: |
            apt-get update -q
            export DEBIAN_FRONTEND=noninteractive
            apt-get install -qy --no-install-recommends nodejs
            nodejs -v
          plugins: |
            fox.jason.extend.css
            https://github.com/dita-bootstrap/dita-bootstrap.html/archive/develop.zip
            fox.jason.prismjs
            fox.jason.favicon
            fox.jason.open-graph
            https://github.com/jason-fox/fox.jason.passthrough/archive/master.zip
            https://github.com/jason-fox/fox.jason.passthrough.swagger/archive/master.zip
            https://github.com/jason-fox/dita-bootstrap.swagger/archive/master.zip
          project: .github/dita-ot/html.xml

      - name: Deploy Documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: out/html
